[package]
name = "wikit-native"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
async-openai = { version = "0.38.0", features = ["chat-completion", "byot"] }
axum = "0.5"
napi = { version = "2.14.3", features = ["tokio_rt"] }
napi-derive = "2.14.3"
once_cell = "1.9.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.0", features = ["full"] }
toml = "1.1.2"
chrono = "0.4"
tower-http = { version = "0.2", features = ["fs"] }
wikit-core = { path = "../../core" }

[build-dependencies]
napi-build = "2.1.0"

[features]
noop = []
