/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function initNativeLogger(logFilePath: string): NapiResult
export interface DictMeta {
  name: string
  id: string
}
export interface LookupResponse {
  words: Record<string, string>
  script: string
  style: string
}
export interface ResourceLookupResponse {
  found: boolean
  mime: string
  url: string
}
export function startStaticFileServer(): NapiResult
export function getDictList(): NapiResult
export function removeLocalDictionary(dictid: string): NapiResult
export function loadLocalDictionary(path: string, progressCallback: (err: Error | null, value: number) => any): Promise<NapiResult>
export function lookup(dictid: string, word: string): NapiResult
export function lookupResource(dictid: string, key: string): NapiResult
export function getTranslationSettings(): NapiResult
export function saveTranslationSettings(settingsJson: string): NapiResult
export function translateText(requestJson: string): Promise<NapiResult>
export function testTranslationConnection(settingsJson: string): Promise<NapiResult>
export function ffiHello(name: string): NapiResult
export function startPreviewServer(dir: string): NapiResult
export function stopPreviewServer(): NapiResult
export function isPreviewServerUp(): NapiResult
export function getConfigDir(): NapiResult
export interface DictInfo {
  id: string
  name: string
  desc: string
  script: string
  style: string
  hasFulltext: boolean
}
export interface SearchEntry {
  word: string
  definition: string
  /** "headword" | "body" */
  kind: string
  snippet: string
}
export function getDictInfo(dictid: string): NapiResult
export function searchDict(dictid: string, word: string): NapiResult
export function republishLocalDictionary(dictid: string, style: string, script: string, outputPath?: string | undefined | null, name?: string | undefined | null, desc?: string | undefined | null): NapiResult
export function buildDictionary(srcfile: string, outfile: string, progressCallback: (err: Error | null, value: number) => any): Promise<NapiResult>
