/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'wikit_native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.android-arm64.node')
          } else {
            nativeBinding = require('@wikit/native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'wikit_native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@wikit/native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'wikit_native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@wikit/native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'wikit_native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@wikit/native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'wikit_native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@wikit/native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'wikit_native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./wikit_native.darwin-universal.node')
      } else {
        nativeBinding = require('@wikit/native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'wikit_native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.darwin-x64.node')
          } else {
            nativeBinding = require('@wikit/native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'wikit_native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.darwin-arm64.node')
          } else {
            nativeBinding = require('@wikit/native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'wikit_native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./wikit_native.freebsd-x64.node')
      } else {
        nativeBinding = require('@wikit/native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@wikit/native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@wikit/native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@wikit/native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@wikit/native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@wikit/native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@wikit/native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@wikit/native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'wikit_native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./wikit_native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@wikit/native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'wikit_native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./wikit_native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@wikit/native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { initNativeLogger, startStaticFileServer, getDictList, removeLocalDictionary, loadLocalDictionary, lookup, lookupResource, getTranslationSettings, saveTranslationSettings, translateText, testTranslationConnection, ffiHello, startPreviewServer, stopPreviewServer, isPreviewServerUp, getConfigDir, getDictInfo, searchDict, republishLocalDictionary, buildDictionary } = nativeBinding

module.exports.initNativeLogger = initNativeLogger
module.exports.startStaticFileServer = startStaticFileServer
module.exports.getDictList = getDictList
module.exports.removeLocalDictionary = removeLocalDictionary
module.exports.loadLocalDictionary = loadLocalDictionary
module.exports.lookup = lookup
module.exports.lookupResource = lookupResource
module.exports.getTranslationSettings = getTranslationSettings
module.exports.saveTranslationSettings = saveTranslationSettings
module.exports.translateText = translateText
module.exports.testTranslationConnection = testTranslationConnection
module.exports.ffiHello = ffiHello
module.exports.startPreviewServer = startPreviewServer
module.exports.stopPreviewServer = stopPreviewServer
module.exports.isPreviewServerUp = isPreviewServerUp
module.exports.getConfigDir = getConfigDir
module.exports.getDictInfo = getDictInfo
module.exports.searchDict = searchDict
module.exports.republishLocalDictionary = republishLocalDictionary
module.exports.buildDictionary = buildDictionary
