/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DictMeta {
  name: string
  id: string
}
export interface LookupResponse {
  words: Record<string, string>
  script: string
  style: string
}
export function startStaticFileServer(): NapiResult
export function getDictList(): NapiResult
export function lookup(dictid: string, word: string): NapiResult
export function getTranslationSettings(): NapiResult
export function saveTranslationSettings(settingsJson: string): NapiResult
export function translateText(requestJson: string): Promise<NapiResult>
export function testTranslationConnection(settingsJson: string): Promise<NapiResult>
export function ffiHello(name: string): NapiResult
export function startPreviewServer(dir: string): NapiResult
export function stopPreviewServer(): NapiResult
export function isPreviewServerUp(): NapiResult
export function getConfigDir(): NapiResult
